apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: deployment-name
  name: deployment-name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-name
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deployment-name
    spec:
      containers:
      - image: image-name
        name: image-name
        resources: {}
status: {}
