apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-todolist-deployment
spec:
  selector:
    matchLabels:
      app: my-todolist
  template:
    metadata:
      labels:
        app: my-todolist
    spec:
      containers:
      - name: todo-list
        image: harness/todolist-sample:latest
        ports:
        - containerPort: 8080
